#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating nginx web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE DJANGO SETTINGS
#=================================================
ynh_script_progression "Update $app settings file..."

mail_user="noreply"
secret_key=$(ynh_app_setting_get --key=secret_key)
redis_db=$(ynh_app_setting_get --key=redis_db)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
timezone="$(timedatectl show --value --property=Timezone)"
umap_readonly=$(ynh_app_setting_get --key=umap_readonly)
umap_keep_versions=$(ynh_app_setting_get --key=umap_keep_versions)
umap_default_edit_status=$(ynh_app_setting_get --key=umap_default_edit_status)
umap_default_share_status=$(ynh_app_setting_get --key=umap_default_share_status)
umap_home_feed=$(ynh_app_setting_get --key=umap_home_feed)

ynh_config_add --template="local.py" --destination="$install_dir/umap/settings/local.py"
chmod 400 "$install_dir/umap/settings/local.py"
chown "$app:$app" "$install_dir/umap/settings/local.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
