#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating nginx web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE DJANGO SETTINGS
#=================================================
ynh_script_progression "Update $app settings file..."

ynh_config_add --template=".env.example" --destination="$install_dir/umap/settings/.env"
chmod 400 "$install_dir/umap/settings/.env"
chown "$app:$app" "$install_dir/umap/settings/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
