#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#-------------------------------------------------
# config_panel.toml settings:

if [ -z "$debug_enabled" ]; then
	debug_enabled="0"
	ynh_app_setting_set --key=debug_enabled --value="$debug_enabled"
fi

if [ -z "$log_level" ]; then
	log_level="WARNING"
	ynh_app_setting_set --key=log_level --value="$log_level"
fi

if [ -z "$admin_email" ]; then
	admin_email="${admin}@${domain}"
    ynh_app_setting_set --key=admin_email --value="$admin_email"
fi

if [ -z "$default_from_email" ]; then
	default_from_email="${app}@${domain}"
	ynh_app_setting_set --key=default_from_email --value="$default_from_email"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop" --log_path="$log_file"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring systemd service '$app'..."

ynh_config_add_systemd

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Setup Python virtualenv for $app ..."
cp ../conf/install_python.py "$data_dir/install_python.py"
cp ../conf/setup_python.py "$data_dir/setup_python.py"
cp ../conf/requirements.txt "$data_dir/requirements.txt"
myynh_setup_python_venv

#=================================================
# copy config files
# ================================================
ynh_script_progression "Create project configuration files..."

ynh_app_setting_set_default --key=default_longitude --value="2.0"
ynh_app_setting_set_default --key=default_latitude --value="51.0"
ynh_app_setting_set_default --key=default_zoom --value="6"
ynh_app_setting_set_default --key=openrouteservice --value=""
ynh_config_add --template="settings.py" --destination="$data_dir/settings.py"
ynh_config_add --template="setup_user.py" --destination="$data_dir/setup_user.py"
ynh_config_add --template="env" --destination="$data_dir/env"

#=================================================
# MIGRATE APP
#=================================================
ynh_script_progression "migrate/collectstatic/createadmin..."

cd "$data_dir" || exit

set -a
. $data_dir/env
set +a

# Just for debugging:
$data_dir/.venv/bin/umap diffsettings

$data_dir/.venv/bin/umap migrate --no-input
$data_dir/.venv/bin/umap collectstatic --no-input

# Create/update Django superuser (set unusable password, because auth done via SSOwat):
$data_dir/.venv/bin/umap create_superuser --username="$admin" --email="$(ynh_user_get_info --username="$admin" --key=mail)"

# Check the configuration
# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
$data_dir/.venv/bin/umap check --deploy || true

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx
ynh_config_add_systemd
ynh_config_add_logrotate "$log_file"
yunohost service add --description $app $app

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Set $app file permissions..."
myynh_fix_file_permissions

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action=restart --log_path=systemd

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
