#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# copy config files
# ================================================
ynh_script_progression "Create project configuration files..."

# Get a new redis db
redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

admin_mail=$(ynh_app_setting_get --app=$app --key=admin_mail)
timezone=$(ynh_app_setting_get --app=$app --key=timezone)
secret_key=$(ynh_app_setting_get --app=$app --key=secret_key)
mail_user="noreply"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="umap/settings/.env"

#=================================================
# MIGRATE APP
#=================================================
ynh_script_progression "Deploying $app..."

pushd $install_dir
    source venv/bin/activate
    pip install --upgrade
    ynh_config_add --template="base.py" --destination="$install_dir/umap/settings/base.py"
    python manage.py migrate
    python manage.py collectstatic --noinput
    deactivate
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Create maps with OpenStreetMap layers" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
